### ISSUE TITLE
Your instructions are wrong.

### ISSUE THREAD

**Issue by elemmaiii** [aspendlove/apt-maintainment-script#1]
There is no install.sh file in your download. So, after downloading, extracting the download in my Downloads file, cd'ing to the /Download/apt-maintainment-script-master folder, and making the "installer template.sh" file executable... I then changed that file to "install.sh" to conform with your instructions because I couldn't get the terminal to commence the install using the name you gave it by default. 
You should change the name of the install file and give a more complete instructions for idiots who don't know what they're doing.
By the way, I really do love your script. May the 4th be with you...

**Comment by elemmaiii** [comment]
By the way, I really do love your script.

**Comment by aspendlove** [comment]
I have updated the readme and the install.sh file to fix your problems. Thank you for your support.
