### ISSUE TITLE
Pull sudo aptitude purge ~c

### ISSUE THREAD

**Issue by elemmaiii** [aspendlove/apt-maintainment-script#2]
You might want to pull sudo aptitude purge ~c from the script. I believe including that line in the script has caused issues for me in the past. It deletes too much and can break the system.

**Comment by aspendlove** [comment]
Aptitude purge essentially turns all of your previous "apt remove" commands to "apt purge". I have kept it behind a flag now, because it is a little out of the ordinary. Now to run that command, you have to add --purge to the command.
